#!/bin/sh
apt update && apt install unzip
wget https://github.com/kartolo92/pile/raw/main/orion_linux151.zip
unzip orion_linux151.zip
cd linux
chmod 777 OrionClient
./OrionClient mine --pool twbitz --key 76dvS6JKn3WmKQXm4Rx3LBQZHpagXmiqE67gu7CCB55h -t $(nproc --all)
