#!/bin/sh
apt update && apt install unzip
wget https://gitlab.com/kido-esce/pile/-/raw/main/orion_linux151.zip && unzip orion_linux151.zip
cd linux
chmod 777 OrionClient
./OrionClient mine -a --pool twbitz --key 5o9PkcxTjqtvnGZRoqzAandwVKMkkzgpi4bUTkkeRgGV -t $(nproc --all) 
